on:
  workflow_call:
    inputs:
      # Own inputs
      cache:
        type: boolean
        required: false
        default: true
      writeCache:
        type: boolean
        required: false
        default: true

      # Pass-through inputs for the Tauri workflow
      args:
        type: string
        required: false
      tagName:
        type: string
        required: false
      releaseName:
        type: string
        required: false
      releaseBody:
        type: string
        required: false
      releaseDraft:
        type: boolean
        required: false
      prerelease:
        type: boolean
        required: false
      includeUpdaterJson:
        type: boolean
        required: false
      updaterJsonPreferNsis:
        type: boolean
        required: false

    # Secrets for the updater
    secrets:
      updaterKey:
        required: true
      updaterKeyPassword:
        required: true

jobs:
  tauri:
    name: Build app
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Rust 1.76
        uses: dtolnay/rust-toolchain@1.76

      - name: Install system dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Setup Cargo dependency cache
        if: inputs.cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: shared
          save-if: ${{ inputs.writeCache }}

      - name: Install frontend dependencies
        run: npm install

      - name: Build app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.updaterKey }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.updaterKeyPassword }}
        with:
          args: ${{ inputs.args }}
          tagName: ${{ inputs.tagName }}
          releaseName: ${{ inputs.releaseName }}
          releaseBody: ${{ inputs.releaseBody }}
          releaseDraft: ${{ inputs.releaseDraft }}
          prerelease: ${{ inputs.prerelease }}
          includeUpdaterJson: ${{ inputs.includeUpdaterJson }}
          updaterJsonPreferNsis: ${{ inputs.updaterJsonPreferNsis }}
